# Generated by Django 4.0.1 on 2022-11-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_is_paid_profile_is_paid_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='main/img/profile/default.png', null=True, upload_to='main/img/profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biogrophy'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='inspo',
            field=models.TextField(blank=True, null=True, verbose_name='Inspirations'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Location'),
        ),
    ]
